### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by dennorske** [pysamp/PySAMP#28]
Hi!

How to install the python package? 

There's no documentation on that, so I am partially stuck.

**Comment by biggerThan-1** [comment]
I was looking for that too.

**Comment by habecker** [comment]
Hey, sorry for my late response. Are you using Windows or Linux?

It should be this simple: Copy the precompiled plugin, install 32-bit Python3, create a python/ subfolder in your servers directory and insert both files from https://github.com/habecker/PySAMP/tree/master/gamemodes/empty there.

But if you still have problems I will do a clean installation on my own, so I can write a better tutorial.

**Comment by dennorske** [comment]
Thanks for the help, I'm on Linux, looking for the file to import into the code. Please add to documentation as well :)

**Comment by dennorske** [comment]
Hi - to bump this, where are the pysamp library at? 

![image](https://user-images.githubusercontent.com/3287543/61044273-920b7a80-a3d8-11e9-9e73-4910cf050889.png)

this is inside samp.py, but there are no pysamp folder nor file in the directory - and nothing to find on pip.
I am interested in contributing but the current documentation is absolutely terrible.

**Comment by habecker** [comment]
> Hey, sorry for my late response. Are you using Windows or Linux?
> 
> It should be this simple: Copy the precompiled plugin, install 32-bit Python3, create a python/ subfolder in your servers directory and insert both files from https://github.com/habecker/PySAMP/tree/master/gamemodes/empty there.
> 
> But if you still have problems I will do a clean installation on my own, so I can write a better tutorial.

If you followed this small guide you should be able to start the server as usually.
The server will then run the gamemode.py file in the python/ directory. The pysamp library itself is served by the server-plugin. Does this answer your question? Sorry for the bad documentation, I currently don't have much time.

**Comment by simeneriks1** [comment]
Oh so pysamp is a runtime library! 
That makes sense, as it serves the functions you are returning in samp.py - I see i see.

I will do some testing and share my learnings in a "How to get started.md" contribution to the repo, if you take pull requests.

**Comment by dennorske** [comment]
Oh so pysamp is a runtime library!
That makes sense, as it serves the functions you are returning in samp.py - I see i see.

I will do some testing and share my learnings in a "How to get started.md" contribution to the repo, if you take pull requests.

**Comment by SodaDesu** [comment]
Hi! The whole project seems really interesting since I saw it but without documentation I'm getting confused.. I did your little setup above but getting random error while compilin' gamemode.py: 'AttributeError: module 'pysamp' has no attribute 'Const' '. Or maybe I'm compiling wrong py's. I did differently but result gets the same. Would be really great if you do a little more detailed about step by step setup(Which main files to download and path into server, which files compile and how to run it on main server). Thanks tho.

**Comment by dennorske** [comment]
What version of python are you using @SodaDesu ? 
As how i understand it (did not have time to go through properly yet) you need to write the code first - lets say you are using the included gamemode.py.
1. Write code
2. Run server
3. Hope it works

I dont see any compile/run step in this situation..

I dont know any way to compile/run the code when you script it, since the **pysamp** library is served by a server plugin on _runtime_.

Also to @habecker: not being able to compile or run through the code before running the server is bad. What about adding a static pysamp that serves the functions when you run the code in development? It is hard to detect bugs, mistakes and such and gives no real advantage over pawn.

**Comment by iPurya** [comment]
i really wish to get simple help (Step by step). i really really need this.

**Comment by dnfive** [comment]
How can i used my favourite modules? Such as: dc_cmd and etc

**Comment by dennorske** [comment]
I am afraid that custom modules can't be easily embedded into the python code. Someone has to write a wrapper for the various modules. I intend to get back to this project very shortly, hopefully I can give you a better answer then

**Comment by tiditik** [comment]
If you don't understand how to do it, you can please make a video clip on creating a simple example of a mod :) Please :)

**Comment by dennorske** [comment]
Hi Timur! What do you mean by mod? Do you need more information how to create a script?

**Comment by tiditik** [comment]
but how to compile a mod?

**Comment by tiditik** [comment]
Error ? :( 
![image](https://user-images.githubusercontent.com/69196938/96181829-45004780-0f3d-11eb-8672-788e9f80c754.png)

**Comment by tiditik** [comment]
Ahhh, is this like a plugin? How do I install it on my server? :)
I just got it ..

**Comment by dennorske** [comment]
When you run the gamemode, the module you're importing will be found by the server plugin. Read this reply: https://github.com/habecker/PySAMP/issues/28#issuecomment-510434256
