### ISSUE TITLE
Python 3.5 no longer default on python3 branch on ubuntu.

### ISSUE THREAD

**Issue by dennorske** [pysamp/PySAMP#32]
Discovering during a setup on docker that python3-dev installs the latest 3.6 and 3.7 libs instead of 3.5 - causing the server not starting properly with the following error:

```log
Loading plugin: pySAMP.so
[11:10:05]   Failed (libpython3.5m.so.1.0: cannot open shared object file: No such file or directory)
```

My recommendation is to check out the instructions here: https://stackoverflow.com/a/38393177

It lets you know alternative ways to install python 3.5 - or you can update the plugin to look for alternative versions.

**Comment by habecker** [comment]
Just tested this with ubuntu 18.04 and I can confirm it. I tried to compile the project for 32bit Python 3.6 and it worked but I wasn't able to install pip. Therefore I would recommend to stick with Ubuntu 16.04 or install Python 3.5 (i386!) manually.

**Comment by dennorske** [comment]
Can we expect an update to the package to make this work?
