### ISSUE TITLE
Folder tree problem

### ISSUE THREAD

**Issue by yaroslav-lev-dev** [pysamp/PySAMP#47]
Hi!

My problem is that I did not understand how to install this project in the directory with the server.

I just transferred everything from the folder, and launched the necessary <.bat> - as a result of which there are errors in the absence of an interpreter, and also the built-in <.amx> mods are loaded, but not those that are on the python.

I ask you to attach a ready-made directory of server files (it doesn't matter Linux or Windows) so that I can figure it out!

**Comment by habecker** [comment]
Hi!
It should actually as easy as putting the bat into the server dir and using it as a server launcher.
What is the console output if you start the bat?

**Comment by yaroslav-lev-dev** [comment]
`[22:39:18] I couldn't load any gamemode scripts. Please verify your server.cfg
[22:39:18] It needs a gamemode0 line at the very least.`

The server log ends with the fact that the mod was not found.
I have the following gamemodes folder structure:
![image](https://user-images.githubusercontent.com/58698069/111857689-f7a55d80-8954-11eb-8923-d73d2a3dea9a.png)

**Comment by habecker** [comment]
The python gamemode is not a real amx gamemode. It's a separate thing and located in a `python/` directory.
Could you try the following?
1. Download a fresh samp03 server and unzip it
2. Put the pysamp-launcher.bat directly into the server directory, so it lies beside the `samp-server.exe` and `server.cfg`
3. Start the pysamp-launcher.bat

This should start the server with an empty amx gamemode and a python directory where an example pysamp gamemode is located.

And whenever you want to start the server again, use the pysamp-launcher.bat as it does a lot of environment configuration and prechecks.

If this still fails, you could join the [discord](https://discord.gg/puw5VeQtbx), where I can help you more directly :)

**Comment by yaroslav-lev-dev** [comment]
Well thank you!

But now I have another problem related to <pysamp-launcher.bat>.
The screenshot shows the whole essence of the problem!

![image](https://user-images.githubusercontent.com/58698069/111882127-a25d6080-89d5-11eb-9cf2-e97d6ce83d34.png)

**Comment by habecker** [comment]
Okay this is interesting. I don't understand russian, but it looks like a SSL problem when the launcher tires to download the python interpreter from python.org

**Comment by habecker** [comment]
Does the launcher from this zip work? It just contains a minor change to enable TLS1.2 connections before downloading the python interpreter and pysamp plugin and so on

I'll create an installer in the future so we don't have to rely on a batch file anymore

[pysamp-launcher.zip](https://github.com/habecker/PySAMP/files/6177496/pysamp-launcher.zip)

**Comment by yaroslav-lev-dev** [comment]
**Great, problem solved and everything works great!

Thank you very much for the quick interaction!**

_```
NickName in Game's: Yaroslav_Magiev
VK: vk.com/y_dev
Skills: pawn, python, web
```_
