### ISSUE TITLE
Native Support

### ISSUE THREAD

**Issue by habecker** [pysamp/PySAMP#49]
To support calling natives from other plugins and getting callbacks for other plugins to work (like FCNPC) we need to implement native support in the plugin.

**Comment by Cheaterman** [comment]
cf1057ab0 partially closes this - no support for callbacks yet, but conceptually it shouldn't be too hard: provide a way for the user to register/unregister callbacks in `callback_format` (see `src/bindings/callbacks.h`)

**Comment by dennorske** [comment]
I am fairly sure that this has been addressed in cf1057ab0c9a6cd50a0d18512c95817cb42ee899 - instead of natively calling, we can wrap the "CallNativeFunction" in python, and use it that way.
Down the line it would be fun to provide modules that cover the most common plugins.
