### ISSUE TITLE
SA-MP server refuses to stop with normal interrupt signal

### ISSUE THREAD

**Issue by dennorske** [pysamp/PySAMP#54]
There's an issue when asyncio code is being used with the plugin and when ^C as interrupt signal (SIGINT) is sent.

Server log will show the following: 
![image](https://user-images.githubusercontent.com/3287543/113583960-9525b000-962a-11eb-8e1c-15569f6d9cb2.png)

As you mentioned @habecker - the sub-processes doesn't stop. I consider this a bug, and a fix would be nice :) 

The side effects are that game panels hosting SA-MP servers will need to issue force-kill signals in order to stop the server.

**Comment by Cheaterman** [comment]
I'm faiiirly sure 126de6b1 closes this, given the commit message mentions deadlocks on exit. Can you please confirm & close @dennorske ?

**Comment by Cheaterman** [comment]
@dennorske (is it working?)

**Comment by dennorske** [comment]
I will test this evening, haven't checked in a while so I don't remember. Keeping you posted.

**Comment by dennorske** [comment]
Confirmed fixed :)
