### ISSUE TITLE
Cyrillic and other languages except English raise error

### ISSUE THREAD

**Issue by extraspeed** [pysamp/PySAMP#57]
**Describe the bug**
If you try to type Cyrillic text, it causes an error.
![1](https://user-images.githubusercontent.com/9309537/113847495-371ad900-97a0-11eb-8680-7e495691e010.PNG)

To solve this problem, you need to put the name of the encoding in a separate parameter. (For example, make a file settings.py, where will be the settings of the gamemod)

For Cyrillic encoding is needed "cp1251"
![2](https://user-images.githubusercontent.com/9309537/113848299-ff606100-97a0-11eb-9f38-b6dd12e9c56e.PNG)
![3](https://user-images.githubusercontent.com/9309537/113848315-01c2bb00-97a1-11eb-8a2d-fc0e9c8dc1c2.PNG)

**Comment by dennorske** [comment]
Thanks for the good report!

Will follow up on this and make the samp.py support a setting like that :+1:

**Comment by Cheaterman** [comment]
It's a great report indeed - in fact I did notice these parameters being iso-8859-1 everywhere, even though SAMP internally use Windows codepage charsets (CP1252 for me, CP1251 for OP obviously). I'm honestly wondering how to address this in a friendly, international way... If we were serious about this, IMHO, we wouldn't have a charset config file, but rather do decoding attempts until we find something that works? Possibly using chardet ( https://pypi.org/project/chardet/ )? That's something I might actually touch upon soon - I'm French, we need our éèàùç etc :-)

**Comment by Cheaterman** [comment]
As it turns out, we now use CP1252 internally since 8853f7b, but we would need to add a setting (perhaps in the form of getter/setter functions on the pysamp module) to allow the end-user to change this and properly close this issue

**Comment by Cheaterman** [comment]
Proposal:
```python
pysamp.config(encoding='cp1251') 
```

**Comment by Cheaterman** [comment]
@extraspeed I don't know if you are able to build PySAMP from source, but #75 should probably help you, I was able to send myself French and Russian characters depending on config :-) - if you can't build from source it's fine, I think we will make a release relatively soon!
