### ISSUE TITLE
OnDialogResponse blocked in AMX no matter what you return in Callback.

### ISSUE THREAD

**Issue by dennorske** [pysamp/PySAMP#58]
**Describe the bug**
The callback OnDialogResponse() does not get called in an AMX compiled game-mode, when you run PySAMP.
Was confirmed by me and two others. 

**To Reproduce**
1. Make an AMX game-mode with using pawn where you add a print in the callback. Add code to show a dialog.
2. Enable PySAMP on the server
3. Launch the server, try to get the print working. Print never calls (hence callback never called in AMX).
4. It, however, calls in the Python game-mode. You can return True and False, both give same results.

**Expected behavior**
Expected the python gamemode to forward the callback to different scripts. Is PySAMP hijacking it from the game-mode?
Tried to check default return value here: https://github.com/habecker/PySAMP/blob/main/src/bindings/callbacks.h#L74 - It is 0 here as well, as expected per docs: https://sampwiki.blast.hk/wiki/OnDialogResponse
![image](https://user-images.githubusercontent.com/3287543/114083397-36249d00-98af-11eb-8db0-4115bb21a637.png)

**Additional context**
Tested on PySAMP 1.2.0 and on the non-released PySAMP object oriented branch.

**Comment by dennorske** [comment]
Found related code that may cause the issue:
https://discord.com/channels/800481031072514110/800481031509245974/830225097910124575

```cpp
bool doesStop = callback_return_configuration.count(name) > 0;
        bool result = PySAMP::callback(name, createParameterObject(amx, name, params));
        sampgdk::logprintf("Name: %s || doesStop: %d || result: %d", name, doesStop, result);
        if (doesStop)
        {
                bool stopOnReturnValue = callback_return_configuration.at(name);
                if (result == stopOnReturnValue)
                {
                        sampgdk::logprintf("Name: %s || StopOnReturnValue: %d", name, stopOnReturnValue);
                        *stop = true;
                }
        }
 ```
 
 This returns:
 ```
 [23:25:13] Name: OnDialogResponse || doesStop: 1 || result: 0
[23:25:13] Name: OnDialogResponse || StopOnReturnValue: 0
```

With this code in python gamemode.py:
```py
def OnDialogResponse(playerid, dialogid, response, listitem, inputtext):
    return False
```

**Comment by habecker** [comment]
Should be fixed now
