### ISSUE TITLE
Using print instead of samp.printf for log-printing

### ISSUE THREAD

**Issue by Cheaterman** [pysamp/PySAMP#62]
Hello fellow Pythonistas!

Mostly everything is in the title - stdout/err isn't really used in SAMP, nobody's gonna see their print()s there. Arguably we still need to keep stderr going to the "right" place, maybe someone will need debugging info that should NOT go to the logs.

But other than that - what would you guys think about tying sys.stdout directly to sampgdk::logprintf so that we can freely use built-in print for our debugging or logging? (if you guys like it, I'd be more than willing to examine how we could achieve this and write a PR!)

Thanks in advance :-)

**Comment by dennorske** [comment]
Sounds good to me!

**Comment by Cheaterman** [comment]
With #63 merged, this issue is resolved. :smile:
