### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by FarzinDev0** [pysamp/PySAMP#82]
I Want to create a gamemode with pysamp but I have an issue with that...

Error:
SystemError: <built-in function ShowPlayerDialog> returned NULL without setting an error

My Code:
ShowPlayerDialog(playerid,1,DIALOG_STYLE_INPUT,'SignUp','Text','Continue','Cancel')

I Tried to solve it but...

**Comment by dennorske** [comment]
Hi!

Would love to help you.

Can you advice a little bit on which version of pysamp you are using, and also if you could show the surrounding code as well? (where do you call this?) 

Thanks!

**Comment by FarzinDev0** [comment]
I used version 2 of release(dll file) and used pysamp-luncher.bat for windows...

**Comment by dennorske** [comment]
Can you provide the surrounding code around `ShowPlayerDialog(playerid,1,DIALOG_STYLE_INPUT,'SignUp','Text','Continue','Cancel')` and also tell what you have tried ? :) 

If you haven't seen, we also have a guide how to install python correctly if you haven't seen that.
https://github.com/pysamp/PySAMP/wiki/How-to-get-started-with-python-3.9.7-on-Windows

**Comment by FarzinDev0** [comment]
I Deleted the file of game mode but it is just an if for user file check...

if user.txt not found so do ...

my python is installed correctly...

**Comment by dennorske** [comment]
I'm afraid you need to show us some code in order for us to help you.

**Comment by FarzinDev0** [comment]
The Error in this game mode...

[connection] 192.168.40.29:50706 requests connection cookie.                                                            [connection] incoming connection: 192.168.40.29:50706 id: 0                                                             [join] user has joined the server (0:192.168.40.29)                                                                  TypeError: an integer is required (got type _ConstWrapper)                                                              Traceback (most recent call last):                                                                                        File "C:\Users\farzi\Desktop\LordGame\python\gamemode.py", line 28, in OnPlayerSpawn                                      ShowPlayerDialog(playerid,1,DIALOG_STYLE_INPUT,'SignUp','Text','Continue','Cancel')                                   File "C:\Users\farzi\Desktop\LordGame\python\samp.py", line 989, in ShowPlayerDialog                                      return pysamp.ShowPlayerDialog(playerid, dialogid, style, encode(caption), encode(info), encode(button1), encode(button2))                                                                                                                  SystemError: <built-in function ShowPlayerDialog> returned NULL without setting an error             




and my game mode is :
                                
from samp import *
from const import *

def OnGameModeInit():
    SetGameModeText('PySAMP')
    return True
    
def OnGameModeExit():
    return True

def OnPyUnload():
    OnGameModeExit()
    return True

def OnPyReload():
    OnGameModeInit()
    return True

def OnPlayerConnect(playerid):
    SendClientMessage(playerid, 0xFF000000, "Hello %s from Python" % GetPlayerName(playerid, MAX_PLAYER_NAME.get()))
    
    return True
    
def OnPlayerDisconnect(playerid, reason):
    return True
    
def OnPlayerSpawn(playerid):
    ShowPlayerDialog(playerid,1,DIALOG_STYLE_INPUT,'SignUp','Text','Continue','Cancel')
    return True

**Comment by dennorske** [comment]
The constant you're retrieving is wrong, you should try using

`DIALOG_STYLE_INPUT.get()`

So it becomes
`ShowPlayerDialog(playerid,1,DIALOG_STYLE_INPUT.get(), 'SignUp','Text','Continue','Cancel') `

**Comment by dennorske** [comment]
Awesome! Good luck onwards :) glad it helped!

More documentation is coming soon ™
