### ISSUE TITLE
SetSpawnInfo Usage

### ISSUE THREAD

**Issue by FarzinDev0** [pysamp/PySAMP#83]
another error...

    SetSpawnInfo(playerid,NO_TEAM,240,0,0,0,0,0,0,0,0,0,0)                                                                File "C:\Users\farzi\Desktop\LordGame\python\samp.py", line 19, in SetSpawnInfo                                           return pysamp.SetSpawnInfo(playerid, team, skin, x, y, z, rotation, weapon1, weapon1_ammo, weapon2, weapon2_ammo, weapon3, weapon3_ammo)                                                                                                    SystemError: <built-in function SetSpawnInfo> returned NULL without setting an error

**Comment by FarzinDev0** [comment]
I just want to remove class choosing...
I want to make player spawned after logging in...

**Comment by FarzinDev0** [comment]
All of consts have to be with .get?

**Comment by dennorske** [comment]
Yes, in your case.

Try updating the plugin / modules with the newer version (2.0) and it may be possible without.

**Comment by FarzinDev0** [comment]
If i do this i have to rewrite my game mode and change consts...

**Comment by FarzinDev0** [comment]
Do I have to write my funca with async?

**Comment by dennorske** [comment]
You functions are only asynchronous if your code requires it. Pysamp in itself is not asynchronous, sadly.
