### ISSUE TITLE
Conflict between pawn and python

### ISSUE THREAD

**Issue by IsProdigy** [pysamp/PySAMP#87]
Apparently it's not possible to use pawn with python, because pawn is a programming language that requires a compilation, unlike python. So after compiling pawn with python an error will result.

**Example:**

```i
public OnGameModeInit()
{

    print("\n-------------------------------------");
    print("Server started!");
    print("-------------------------------------\n");
    return 1;
}

def OnGameModeExit()
    print("\n-------------------------------------"):
    print("Server shut down!"):
    print("-------------------------------------\n"):
    return True
```
I was thinking of connecting a discord bot with python and controlling it through the samp server, but I think this is impossible since there is no way to use pawn and python in the same code.
    If there was a way to use both programming languages ​​in a code together, it would be great, because there are people like me with the server already ready, and I would have to recreate the same in python.
    How would it be to use the includes with the plugins?

**Comment by dennorske** [comment]
Hi!

Pysamp is just a plugin. That means the amx gamemode will still load and do what you want it to do.
Try to load it up using a normal amx gamemode, and then also make a small python gamemode in the python file and load that via the plugin. It should not be in the same file  :)

See step two here for cfg:
https://github.com/pysamp/PySAMP#servercfg-details

**Comment by IsProdigy** [comment]
OK thank you.
