### ISSUE TITLE
Docker problem

### ISSUE THREAD

**Issue by UHPS** [pysamp/PySAMP#90]
Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy/main/binary-i386/Packages  404  Not Found

**Comment by dennorske** [comment]
Hi and welcome to PySAMP, Thanks for posting the issue!

Can you provide a little more context to what you are doing?
Are you running the default docker setup? :) 
What command are you running to start the docker setup?

Thanks!

**Comment by UHPS** [comment]
Hello. I installed docker, and running Docker/run.sh

![Снимок экрана 2022-07-17 в 17 01 19](https://user-images.githubusercontent.com/29305589/179401899-84332b54-e0c2-4555-8a5f-3d8f9420270f.png)

**Comment by UHPS** [comment]
P.s. im trying change "FROM i386/ubuntu"

But have other error 

#6 108.1 Cloning into 'samp-plugin-sdk'...
#6 109.8 Cloning into 'PySAMP'...
#6 112.0 Reading package lists...
#6 116.8 Building dependency tree...
#6 117.5 Reading state information...
#6 117.7 E: Unable to locate package python2

**Comment by dennorske** [comment]
Not sure why you cannot fetch the packages, it works just fine for me pulling the repo.

CAn you verify you are not on a bad network or have bad dns configuration?

**Comment by UHPS** [comment]
I trying change to 8.8.8.8 DNS, trying connect via mobile internet. Same problem

#6 7.969 Fetched 21.0 MB in 8s (2705 kB/s)
#6 7.969 Reading package lists...
#6 7.977 E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy/main/binary-i386/Packages  404  Not Found [IP: 185.125.190.36 80]
#6 7.977 E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy-updates/main/binary-i386/Packages  404  Not Found [IP: 185.125.190.36 80]
#6 7.977 E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy-backports/universe/binary-i386/Packages  404  Not Found [IP: 185.125.190.36 80]
#6 7.977 E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy-security/restricted/binary-i386/Packages  404  Not Found [IP: 185.125.190.36 80]
#6 7.977 E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by dennorske** [comment]
We notice that you are running (most likely) on an M1/M2 (ARM) based CPU that most likely is causing this. Because of this, your docker is pulling an image that runs natively on that architecture.

Please read here: https://docs.docker.com/desktop/mac/apple-silicon/#known-issues

You need to force your docker to download the x86 images and run those under emulation. 
Try adding this flag to your `run.sh`: 
```
--platform linux/amd64
```
Reference (docker run): https://docs.docker.com/engine/reference/commandline/run/

**Comment by Cheaterman** [comment]
If I missed it somewhere, please let me know @UHPS since I can't test that here.
